### ISSUE TITLE
De functie `RandomMove` werkt niet in 99% van de gevallen

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Brian-Boersen/educom-csharp-algorithm-1685534691#4]
De code voor RandomMove is niet correct, het pakt nu een random nummer tussen -2147483648 en 2147483647 en gaat dan een move met dat id zoeken. in 99.99% van de gevallen levert dit geen move op
https://github.com/Brian-Boersen/educom-csharp-algorithm-1685534691/blob/ed68e9a98d08962f2ab92d5ebd3a8787ac5d441c/BornToMove.Business/BuMove.cs#L15-L20

Wat je moet doen is eerst bij de crud alle id's van moves opvragen, uit die lijst een random getal kiezen en daarna de hele move opzoeken.

**Comment by Brian-Boersen** [comment]
all veranderd
